### ISSUE TITLE
"AntFall" "AntGather" environemnt import error

### ISSUE THREAD

**Issue by RushToNeverLand** [AboudyKreidieh/h-baselines#148]
Maybe there are some mistakes when using envs from "efficient-hrl",  I guess maybe it mainly for compatible problem?
Error information:
AttributeError: 'AntFall' object has no attribute 'wrapped_env'

**Comment by RushToNeverLand** [comment]
Sorry, my mistake.
It's just something of dependency, I have solved it. Thank you for your code!

**Comment by AboudyKreidieh** [comment]
hi @RushToNeverLand thanks for the catch! I haven't been using the AntFall and AntPush environments as I was struggling to recreate the results a few months ago. I will try to look into it soon and get it working again.

In terms of the AntGather environment, I hope that one worked out well. I've also recently added a description of how I modified the xml file and env in rllab to render it more similar to the "efficient-hrl" tasks. If you're having problems recreating results you may want to follow these [instructions](https://github.com/AboudyKreidieh/h-baselines#13-importing-antgather).

**Comment by AboudyKreidieh** [comment]
Update on the AntFall environment: It looks like the environment was falling based on an inappropriately defined "dying" condition. I've resolved it in PR #154, will merge to master once tests pass.
