### ISSUE TITLE
What's the use of 'evaluate' in AntMaze env?

### ISSUE THREAD

**Issue by RushToNeverLand** [AboudyKreidieh/h-baselines#160]
In AntMaze env, if 'evaluate' is true then there will be 3 AntMaze env with different context goal. Is the use of 'evaluate' testing the performance of agent instead of training?

**Comment by Hotwaterman** [comment]
I have the same question, do you get it now？

**Comment by brandontrabucco** [comment]
Yes, the evaluate setting is for testing the performance of a trained agent on three different evaluation goals at three different positions throughout the maze. These evaluation environments have fixed goals, whereas the training environment randomly samples its goal when the episodes reset.
